name: Build & Package Face Recognition App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # or macos-latest for native camera builds

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller main.py \
          --add-data "shape_predictor_68_face_landmarks.dat:face_recognition_models/models" \
          --add-data "shape_predictor_5_face_landmarks.dat:face_recognition_models/models" \
          --add-data "dlib_face_recognition_resnet_model_v1.dat:face_recognition_models/models" \
          --add-data "mmod_human_face_detector.dat:face_recognition_models/models" \
          --noconfirm

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: face-recognition-dist
        path: dist/
